mystr: defaultEnv
server:
 port: 9001
spring:
  profiles:
    active: dev
---
mystr: DevEnv
spring:
  profiles: dev
server:
 port: 9002


---
mystr: prodEnv
spring:
  profiles: prod
server:
 port: 9003